# This workflow will build a kuberneties cluster, deploy License Service instance
# and run certification tests to confirm basic functionality
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to Settings | Secrets: IBM_CLOUD_API_KEY and IKS_CLUSTER_API_KEY
# 3. Change the values for the env variables


name: Build and Deploy to IKS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow
env:
  #GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: eu-de
  IBM_CLOUD_RESOURCE_GROUP: Default
  IKS_CLUSTER_NAME: ls_cluster_MB
  IKS_CLUSTER_ZONE: dal10
  IKS_CLUSTER_PRIVATE_VLAN: 2887074
  IKS_CLUSTER_PUBLIC_VLAN: 2887072
  #IKS_CLUSTER_FLAVOR: b2c.4x16
  IKS_CLUSTER_FLAVOR: u3c.2x4
  IKS_CLUSTER_API_KEY: ${{ secrets.IKS_CLUSTER_API_KEY }}
  IKS_CLUSTER_TAG_NAMES: owner:marta.bereta,team:CP4MCM,Usage:temp,Usage_desc:'Certification tests',Review_freq:month

#  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
#  IBM_CLOUD_REGION: eu-de
#  IBM_CLOUD_RESOURCE_GROUP: Default
#  IKS_CLUSTER_NAME: mycluster-ls
#  IKS_CLUSTER_ZONE: fra02
#  IKS_CLUSTER_PRIVATE_VLAN: 2887074
#  IKS_CLUSTER_PUBLIC_VLAN: 2887072
#  IKS_CLUSTER_FLAVOR: u3c.2x4
#  IKS_CLUSTER_API_KEY: ${{ secrets.IKS_CLUSTER_API_KEY }}
#  IKS_CLUSTER_TAG_NAMES: owner:marta.bereta,team:CP4MCM,Usage:temp,Usage_desc:'Certification tests',Review_freq:month

  DEPLOYMENT_NAME: iks-release
  #PORT: 5001

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Download and Install IBM Cloud CLI
    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        ibmcloud plugin install -f container-registry

    # Authenticate with IBM Cloud CLI
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g "${IBM_CLOUD_RESOURCE_GROUP}"
        ibmcloud cr region-set "${IBM_CLOUD_REGION}"
        ibmcloud cr login

    # Check if the particular cluster exists
    - name: Check if k8s exists
      id: cluster_existence
      run: ibmcloud ks cluster ls | grep -e $IKS_CLUSTER_NAME[[:space:]]

    # Create k8s cluster
    - name: Create K8s
      if: ${{ failure() }}
      run: |
        ibmcloud target -g $IBM_CLOUD_RESOURCE_GROUP
        ibmcloud ks cluster create classic --name $IKS_CLUSTER_NAME --zone $IKS_CLUSTER_ZONE --flavor $IKS_CLUSTER_FLAVOR --hardware shared --workers 1 --public-vlan $IKS_CLUSTER_PUBLIC_VLAN --private-vlan $IKS_CLUSTER_PRIVATE_VLAN
        ibmcloud resource tag-attach --resource-name $IKS_CLUSTER_NAME --tag-names $IKS_CLUSTER_TAG_NAMES
      # ibmcloud ks cluster create classic --zone $IKS_CLUSTER_ZONE --private-vlan $IKS_CLUSTER_PRIVATE_VLAN --public-vlan $IKS_CLUSTER_PUBLIC_VLAN --flavor $IKS_CLUSTER_FLAVOR --name $IKS_CLUSTER_NAME --hardware shared --workers 2

      # Use existing k8s cluster
    - name: Use existing k8s cluster
      if: ${{ success() }}
      run: echo 'The cluster ' $IKS_CLUSTER_NAME ' will be used'

    - name: Check K8s
      run: ./scripts/check_cluster.sh $IKS_CLUSTER_NAME

    - name: Cluster connection
      run: |
        ibmcloud login --apikey $IKS_CLUSTER_API_KEY
        ibmcloud target -g Default

    - name: Download LS repository
      run: git clone https://github.com/IBM/ibm-licensing-operator.git

    - name: kubectl installation and configuration
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        ibmcloud ks cluster config --cluster $IKS_CLUSTER_NAME
        kubectl config current-context

    - name: Install License Service
      run:  ./ibm-licensing-operator/common/scripts/ibm_licensing_operator_install.sh --olm_global_catalog_namespace ibm-common-services

    - name: Download Common Services Sanity Tests repository
      run: git clone https://github.ibm.com/IBMPrivateCloud/common-svcs-sert-tests

    - name: Configure
      run: |
        ibmcloud login --apikey "uSR4X8ZcV_anySOrLAFF0jBYrrGOa5ujeRM7f0DnBeP

    - name: Install BATS (for tests purpose)
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        ./install.sh /usr/local

    - name: Configure tests
      run: |
        export OC=kubectl



    # Build the Docker image
#    - name: Build with Dockerfvfdv
#      run: |
#        docker build -t "$REGISTRY_HOSTNAME"/"$ICR_NAMESPACE"/"$IMAGE_NAME":"$GITHUB_SHA" \
#          --build-arg GITHUB_SHA="$GITHUB_SHA" \
#          --build-arg GITHUB_REF="$GITHUB_REF" .

    # Push the image to IBM Container Registry
#    - name: Push the image to ICR
#      run: |
#        docker push $REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA

    # Deploy the Docker image to the IKS cluster
#    - name: Deploy to IKS
#      run: |
#        ibmcloud ks cluster config --cluster $IKS_CLUSTER  --yaml --admin
#        kubectl config current-context
#        kubectl apply -f deploy.yaml
#        kubectl rollout status deployment/$DEPLOYMENT_NAME



    #   kubectl create service loadbalancer $DEPLOYMENT_NAME --tcp=80:$PORT --dry-run -o yaml > service.yaml
    #   kubectl apply -f service.yaml
    #   kubectl get services -o wide
    #   ibmcloud ks cluster rm  --cluster $IKS_CLUSTER

#        ibmcloud ks cluster config --cluster $IKS_CLUSTER
#        kubectl config current-context
#        kubectl create deployment $DEPLOYMENT_NAME --image=$REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA --dry-run -o yaml > deployment.yaml
#        kubectl apply -f deployment.yaml
#        kubectl rollout status deployment/$DEPLOYMENT_NAME
#        kubectl create service loadbalancer $DEPLOYMENT_NAME --tcp=80:$PORT --dry-run -o yaml > service.yaml
#        kubectl apply -f service.yaml
#        kubectl get services -o wide
